// Traduction anglaise de courtoisie des textes légaux (source : fr.ts).
// En cas de divergence, la version française fait foi (droit français).
// Toute modification de fr.ts doit être répercutée ici.

const COURTESY_NOTE = `This is a courtesy translation provided for convenience. In case of any discrepancy, the French version prevails. These documents are governed by French law.`;

export const LEGAL_UPDATED = 'July 12, 2026';

export const LEGAL_NOTICE_TEXT = `${COURTESY_NOTE}

## 1. Publisher

The Watchy application is published by:

Tom Debout, sole proprietor (entrepreneur individuel), trading under the name "Watchy".

SIREN: 918 898 925
SIRET: 918 898 925 00030

Address: 2 allée Vasco de Gama, 30650 Rochefort-du-Gard, France.

Email: contact@watchy-app.com

Publication director: Tom Debout.

## 2. Hosting

The data required for the operation of the Application is hosted in particular via Supabase, within the European Union, in Germany.

The public web page gathering this information is hosted by: Railway Corporation, 548 Market Street PMB 68956, San Francisco, CA 94104, United States.

## 3. Intellectual property

The Watchy Application, its visual identity, texts, interface, code and graphic elements are protected by applicable intellectual property rights.

Any unauthorized reproduction, representation, adaptation or exploitation of all or part of these elements is prohibited without the prior written authorization of the publisher.

## 4. Contact

For any question relating to the Application, you may contact the publisher at the following address: contact@watchy-app.com.`;

export const TERMS_TEXT = `${COURTESY_NOTE}

## 1. Publisher and purpose

The Watchy application (the "Application") is published by Tom Debout, sole proprietor (entrepreneur individuel), trading under the name "Watchy", whose SIREN is 918 898 925 and SIRET is 918 898 925 00030, domiciled at 2 allée Vasco de Gama, 30650 Rochefort-du-Gard, France.

Contact: contact@watchy-app.com

These General Terms of Use and Sale ("Terms", French "CGUV") govern the use of the Application and, where applicable, subscription to Watchy Premium.

Watchy notably allows you to catalog a watch collection, create a wishlist, obtain indicative analyses and estimates generated by artificial intelligence, and access Premium features.

By creating an account, using the Application or subscribing to a Premium offer, you accept these Terms.

## 2. Access conditions and user account

The Application is reserved for persons aged 15 or over.

Minors aged 15 to 18 must obtain the authorization of their legal representative before subscribing to any paid offer.

The Application may be accessed with an email address, a sign-in provider offered in the Application or, when available, in guest mode.

You are responsible for the accuracy of the information you provide and for the confidentiality of your login credentials.

Guest mode does not constitute a guaranteed means of backup. If the Application is uninstalled, the device is changed or access to it is lost, the data associated with a guest account may no longer be recoverable.

You can delete your account from within the Application. The terms of deletion and data retention are detailed in the Privacy Policy.

## 3. Free offer and Watchy Premium subscription

The free offer includes, depending on the features available in the Application:

- adding up to 5 watches in total, collection and wishlist combined;
- up to 5 watch identifications by artificial intelligence per month;
- an indicative update of each watch's market value approximately every 30 days.

The Watchy Premium subscription includes, depending on the features available in the Application:

- unlimited addition of watches, in both the collection and the wishlist;
- watch identifications by artificial intelligence without quantitative limit, within the scope of normal and reasonable personal use;
- an indicative update of the collection's market value approximately every 7 days;
- optional notifications when the market value of your watches moves (can be disabled from your profile);
- a document storage space (photos of papers, receipts, certificates) attached to your watches.

The features included in each offer, their possible limits and their availability are displayed in the Application before any subscription.

The prices currently offered are as follows:

- Watchy Premium monthly: €4.99 incl. VAT per month;
- Watchy Premium annual: €39.99 incl. VAT per year.

One-time purchases ("packs") may also be offered in the Application, in particular:

- pack of 5 artificial-intelligence identifications: €1.99 incl. VAT;
- pack of 3 additional slots (collection and wishlist combined): €2.99 incl. VAT.

Packs are one-time purchases with no automatic renewal. Identification credits are used after the free monthly quota is exhausted and do not expire; additional slots are permanently acquired for the account. Once consumed, credits are non-refundable, without prejudice to applicable statutory rights and Apple's refund policies.

A 7-day free trial may be offered when indicated at the time of subscription.

The prices displayed in the App Store are those applicable on the date of purchase. They may change for future periods, subject to the information and notification procedures applied by Apple.

## 4. Payment, renewal and cancellation

Watchy Premium subscriptions are purchased, billed and managed exclusively via Apple's App Store.

When a free trial is offered, the subscription becomes paid at the end of that trial, unless cancelled before it ends.

The subscription renews automatically at the end of each period, unless cancelled at least 24 hours before the end of the current period.

Managing or cancelling the subscription is done from your Apple account settings: Settings > your name > Subscriptions.

Cancellation takes effect at the end of the period already paid. You retain access to Premium features until that date.

Refund requests relating to purchases made via the App Store are handled in accordance with Apple's terms and procedures, without prejudice to applicable statutory rights.

## 5. Right of withdrawal and legal guarantee of conformity

Where the law allows, immediate access to Premium features may entail the loss of the right of withdrawal once you have given your express consent to begin performance of the service before the expiry of the withdrawal period and acknowledged this consequence.

The terms applicable to purchases made via the App Store may also depend on Apple's conditions.

You benefit from the legal guarantee of conformity applicable to digital content and services. In the event of a lack of conformity of the Application or Premium features, you may request that they be brought into conformity free of charge, under the conditions provided for by the French Consumer Code.

For any complaint relating to the conformity of the service, contact the publisher at contact@watchy-app.com.

## 6. Analyses, estimates and artificial intelligence

Watchy uses artificial intelligence systems, notably the Anthropic API, to provide watch identifications, detailed analyses and indicative value estimates.

Analyses may take into account the photos and information provided by the user, as well as publicly accessible information obtained through a web search.

The information, analyses, identifications and estimates displayed in the Application are provided for purely informational and indicative purposes.

They do not constitute:

- a horological appraisal;
- a certification of authenticity;
- a guarantee of value;
- a binding valuation for insurance, inheritance, resale or litigation purposes;
- financial, wealth-management or investment advice.

Actual transaction values may differ significantly from the estimates displayed. The identification of a watch from a photo may also be erroneous, incomplete or outdated.

Before any purchase, sale, insurance, inheritance or investment decision, you must have the relevant information verified by a competent professional.

## 7. User-submitted content

The photos, notes and information you add to the Application remain your property.

You nevertheless grant the publisher a non-exclusive, worldwide, free licence, limited to the duration necessary for the provision of the service, to store, process, display and analyze this content for the purposes of the Application.

You warrant that you hold the necessary rights to the content you submit and undertake not to upload content that is unlawful, infringing, defamatory or that violates the rights of third parties.

## 8. Personal data

The conditions under which your personal data is processed are described in the Privacy Policy accessible from the Application.

That policy forms an integral part of these Terms.

## 9. Availability and liability

The publisher makes reasonable efforts to ensure the proper functioning of the Application.

However, the Application may experience interruptions, unavailability, maintenance operations, technical errors or changes to features, in particular due to third-party providers, the App Store, artificial intelligence services or web search services.

The publisher does not warrant that the analyses generated by artificial intelligence are accurate, complete, up to date or suitable for any particular situation.

Subject to mandatory legal provisions applicable to consumers, the publisher cannot be held liable for decisions made solely on the basis of the estimates, analyses or identifications displayed in the Application.

## 10. Account suspension or deletion

The publisher may suspend or delete an account in the event of fraudulent, abusive or unlawful use, or use likely to harm the proper functioning, security or reputation of the Application.

Except in cases of urgency or legal obligation, the user will be informed before any account suspension or deletion.

You may stop using the Application and request the deletion of your account at any time from within the Application.

## 11. Changes to these Terms

These Terms may change to reflect legal, technical, functional or commercial developments of the Application.

The applicable version is the one accessible in the Application on the date of your use.

In the event of a substantial change, the user will be informed by appropriate means before it comes into force, in particular within the Application.

## 12. Governing law and disputes

These Terms are governed by French law.

In the event of a complaint, you may contact the publisher at the following address: contact@watchy-app.com.

Failing prior amicable resolution, you may use a consumer mediator free of charge.

You retain the right to bring proceedings before the competent courts under the conditions of ordinary law.`;

export const PRIVACY_TEXT = `${COURTESY_NOTE}

## 1. Data controller

The data collected via the Watchy application is processed by:

Tom Debout, sole proprietor (entrepreneur individuel), trading under the name "Watchy".

SIREN: 918 898 925
SIRET: 918 898 925 00030
Address: 2 allée Vasco de Gama, 30650 Rochefort-du-Gard, France.

Contact for personal data matters: contact@watchy-app.com

## 2. Data collected

Depending on your use of the Application, Watchy may process the following categories of data:

- Account data: email address, technical account identifier and, where applicable, the identifier transmitted by the chosen sign-in provider.
- Optional self-declared profile data: age range, city and country of residence, level of watch knowledge, and the answer to the question "How did you hear about us?". This information is provided freely, can be modified at any time from the Application and does not condition any feature. Watchy never asks for a date of birth or a full postal address.
- Collection data: brand, model, reference, information entered about the watch, purchase price, purchase date, condition, notes and photos.
- Purchase documents (Premium subscribers): photos of papers, receipts or certificates you choose to attach to your watches. These documents are stored in a private space, accessible only from your account via temporary signed links, and deleted with the watch or the account.
- Wishlist data: tracked models and any photos added.
- Data related to artificial intelligence analyses: photos, information about the watch and the requests necessary for identification, analysis or estimation.
- Subscription data: subscription status, plan subscribed, expiry date and technical identifiers transmitted by Apple and RevenueCat.
- Notification data: the technical token required to send push notifications and the device language (to send notifications in your language), when you have authorized them. Premium subscribers may receive automatic market-value alerts, which can be disabled at any time from the profile.
- Technical and security data: information strictly necessary for operation, security, fraud prevention, quota enforcement and incident handling.

Watchy does not collect your banking data. Payments are processed by Apple via the App Store.

Watchy does not use targeted advertising or third-party advertising analytics SDKs.

## 3. Device permissions

The Application may request the following permissions:

- Camera: to take a photo of a watch to add or analyze.
- Photo library: to select an existing photo.
- Notifications: to send you announcements about the Application (new features, important information).

These permissions are optional. You can accept, refuse or change them at any time in your device settings.

## 4. Payment, automatic renewal and cancellation

Watchy Premium subscriptions are purchased, billed and managed exclusively via Apple's App Store.

When a 7-day free trial is offered, no amount is charged during that period. At the end of the free trial, the subscription automatically becomes paid at the displayed price, unless cancelled at least 24 hours before the end of the trial.

The subscription renews automatically at the end of each subscription period, monthly or annual, unless cancelled at least 24 hours before the end of the current period.

The renewal amount is charged to your Apple account within 24 hours before the end of the current period.

Managing, changing or cancelling the subscription is done from your Apple account settings: Settings > your name > Subscriptions.

Cancellation takes effect at the end of the period already paid. You retain access to Premium features until that date.

Refund requests relating to purchases made via the App Store are handled in accordance with Apple's terms and procedures, without prejudice to applicable statutory rights.

## 5. Right of withdrawal and legal guarantee of conformity

Watchy Premium is a digital service provided immediately after subscription.

By subscribing to Watchy Premium and immediately accessing Premium features, the user expressly requests immediate performance of the service before the expiry of the statutory withdrawal period and acknowledges waiving their right of withdrawal, under the conditions provided for by the regulations applicable to digital content and services.

Consequently, where such consent and express waiver have been collected in the applicable purchase flow, the right of withdrawal does not apply once immediate access to Premium features has begun.

This rule does not limit the mandatory rights that consumers enjoy under the law, in particular the legal guarantee of conformity applicable to digital content and services.

You benefit from the legal guarantee of conformity applicable to digital content and services. In the event of a lack of conformity of the Application or Premium features, you may request that they be brought into conformity free of charge, under the conditions provided for by the French Consumer Code.

For any complaint relating to the conformity of the service, contact the publisher at contact@watchy-app.com.

## 6. Retention periods

Your data is retained for as long as you use your account.

When you delete your account from the Application, your account, collection and wishlist data and your photos are deleted or anonymized within a maximum of 30 days, subject to:

- the technical time required for deletion;
- backups retained temporarily according to their normal retention cycle;
- legal retention obligations;
- the need to retain certain elements in the event of a dispute or fraud.

Billing and payment data is managed by Apple in accordance with its own privacy policy and legal obligations.

## 7. Your rights

In accordance with the applicable personal data protection regulations, you have in particular the following rights:

- right of access;
- right to rectification;
- right to erasure;
- right to restriction of processing;
- right to object;
- right to data portability;
- right to withdraw your consent at any time where processing is based on it;
- right to define directives regarding the fate of your data after your death.

You can exercise your rights by writing to contact@watchy-app.com.

You may also lodge a complaint with the CNIL (the French data protection authority).

## 8. Security

Watchy implements reasonable technical and organizational measures to protect your data against loss, unauthorized access, alteration or disclosure.

Exchanges between the Application and its services use encrypted connections. Access to your collection information is limited to your account, subject to the processing necessary for the provision of the service.

As no method of transmission or storage is completely secure, Watchy cannot however guarantee absolute security.

## 9. Minors

The Application is reserved for users aged 15 or over.

Minor users must obtain the authorization of their legal representative before subscribing to any paid offer.

If you believe that a child under 15 has provided us with personal data without appropriate authorization, contact us at contact@watchy-app.com so that we can review the request.

## 10. Changes to this privacy policy

This privacy policy may change to reflect legal, technical or functional developments of the Application.

In the event of a substantial change, users will be informed by appropriate means before it comes into force.`;

export const AI_ANALYSIS_NOTICE_TEXT = `By starting the analysis, you ask Watchy to send the photo of your watch and the information required for its identification to Anthropic, our artificial intelligence provider.

This analysis produces an identification and an estimate that are indicative only. It constitutes neither an authenticity appraisal, nor a binding valuation, nor purchase or investment advice.`;

export const PAYWALL_LEGAL_TEXT = `7-day free trial, then €4.99 per month or €39.99 per year, depending on the selected plan.

The subscription renews automatically at the end of each period, unless cancelled at least 24 hours before the renewal date. The corresponding amount will be charged to your Apple account.

You can manage or cancel your subscription at any time in Settings > your name > Subscriptions.

By subscribing, you accept our Terms of Use and our Privacy Policy.`;
